# Generated by Django 4.2.7 on 2025-07-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_item_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='swap',
            name='requested_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_swaps', to='core.item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together={('user', 'item', 'requested_item')},
        ),
    ]
