# Generated by Django 4.2.7 on 2025-07-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_swap_unique_together_swap_requested_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together={('user', 'item')},
        ),
        migrations.RemoveField(
            model_name='swap',
            name='requested_item',
        ),
    ]
