# Generated by Django 4.2.7 on 2025-07-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_swap_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='point_value',
            field=models.IntegerField(blank=True, help_text='Points required to redeem this item. If empty, item can only be swapped.', null=True),
        ),
        migrations.AddField(
            model_name='swap',
            name='requested_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_swaps', to='core.item'),
        ),
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together={('user', 'item', 'requested_item')},
        ),
    ]
