# Generated by Django 4.2.7 on 2025-07-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_swap_unique_together_item_point_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
